# Generated by Django 5.0.2 on 2024-03-19 22:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_alter_cities_created_at_alter_cities_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('abrev', models.CharField(max_length=20)),
                ('descrip', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 3, 19, 17, 26, 5, 341989))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 3, 19, 17, 26, 5, 341989))),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('abrev', models.CharField(max_length=20)),
                ('descrip', models.CharField(max_length=20)),
                ('ide_country', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 3, 19, 17, 26, 5, 340989))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 3, 19, 17, 26, 5, 340989))),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Identification_types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('abrev', models.CharField(max_length=20)),
                ('descrip', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 3, 19, 17, 26, 5, 338991))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 3, 19, 17, 26, 5, 338991))),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, null=True)),
                ('ide_person', models.IntegerField()),
                ('status', models.BooleanField(blank=True, null=True)),
                ('cre_at', models.DateTimeField(default=datetime.datetime(2024, 3, 19, 17, 26, 5, 337996))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 3, 19, 17, 26, 5, 337996))),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cities',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 19, 17, 26, 5, 339990)),
        ),
        migrations.AlterField(
            model_name='cities',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 19, 17, 26, 5, 339990)),
        ),
        migrations.AlterField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 19, 17, 26, 5, 339990)),
        ),
        migrations.AlterField(
            model_name='person',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 19, 17, 26, 5, 339990)),
        ),
        migrations.AlterField(
            model_name='user',
            name='cre_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 19, 17, 26, 5, 273917)),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 19, 17, 26, 5, 273917)),
        ),
    ]
